version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  lambdas-integration-tests:
    build: "./lambdas"
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - SQS_TEST_QUEUE=http://localhost:4566/000000000000/integration_test_queue
      - UNSUBSCRIPTION_SURVEY_SUBMITTED=arn:aws:sns:us-east-1:000000000000:unsubscription_survey_submitted
