version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  localstack_dynamodbadmin:
    image: instructure/dynamo-local-admin
    networks:
      - default
    depends_on:
      - localstack
    links:
      - localstack
    ports:
      - "8002:8000"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
  lambdas-integration-tests:
    build: "./lambdas"
    environment:
      - ENDPOINT_URL=http://localstack:4566
    env_file:
      .env
